version: '3.8'
services:
  backend:
    image: 
      mattsbitt/capturerr-backend:0.1
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
    - ENVIRONMENT=prod
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
     - ./:/var/www
     - ./nginx/:/etc/nginx/conf.d/
     - /home/matt/.ssl:/etc/nginx/certs
    networks:
      - app-network


  frontend:
    image:
      mattsbitt/capturerr-frontend:0.1
    container_name: frontend
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - '3000:3000'
    restart: always
    networks:
      - app-network


networks:
  app-network:
